Name: locust

image:
  repository: jpmeagher/playground
  tag: docker-locust-0.7.5
  pullPolicy: IfNotPresent

service:
  name: master-web
  type: ClusterIP
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
master:
  config:
    target-host: http://elastic:changeme@es-test-helm-elasticsearch:9200
    corpus-glob: /corpus/*/*.txt
    monitoring-es-url: http://elastic:changeme@monitoring-es-svc:9200/locust
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
worker:
  config:
    monitoring-es-url: http://elastic:changeme@monitoring-es-svc:9200/locust/stat
    # all files from tasks folder are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/tasks.py"
  replicaCount: 6
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
