apiVersion: v1
kind: Service
metadata:
  name: monitoring-es-svc
  labels:
    component: monitoring-es-svc
    role: client
spec:
  type: ClusterIP
  selector:
    component: monitoring-es-cluster
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
