apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-kibana
    spec:
      containers:
      - name: monitoring-kibana
        image: "docker.elastic.co/kibana/kibana:5.6.3"
        imagePullPolicy: "IfNotPresent"
        command: ["/usr/share/kibana/bin/kibana"]
        args: ["-e", "$(ES_URL)", "-l", "/tmp/kibana.log", "--verbose"]
        env:
        - name: ES_URL
          value: http://monitoring-es-svc:9200
        ports:
        - containerPort: 5601
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
