version: '3'
services:
  #db:
  #  image: nouchka/sqlite3:latest
  #  command: my.db
  #  volumes:
  #    - my.db:/my.db
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - ./db:/myapp/db
    ports:
      - "3000:3000"
    #depends_on:
    #  - db
